// <auto-generated />
using System;
using Licitaciones.Infrastructure.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Licitaciones.Infrastructure.Persistencia.Migraciones
{
    [DbContext(typeof(LicitacionesDbContext))]
    [Migration("20260812034325_EsquemaInicial")]
    partial class EsquemaInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Licitaciones.Domain.Entidades.Licitacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("CodigoNormalizado")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo_normalizado");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<int>("Estado")
                        .HasColumnType("integer")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("FechaCierre")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_cierre");

                    b.Property<decimal>("PresupuestoEstimadoCrc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("presupuesto_estimado_crc");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("titulo");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CodigoNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_licitaciones_codigo_normalizado")
                        .HasFilter("deleted_at IS NULL");

                    b.HasIndex("Estado")
                        .HasDatabaseName("ix_licitaciones_estado");

                    b.HasIndex("FechaCierre")
                        .HasDatabaseName("ix_licitaciones_fecha_cierre");

                    b.ToTable("licitaciones", null, t =>
                        {
                            t.HasCheckConstraint("ck_licitaciones_codigo_no_vacio", "length(btrim(codigo)) > 0");

                            t.HasCheckConstraint("ck_licitaciones_presupuesto_positivo", "presupuesto_estimado_crc > 0");
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.NivelAprobacion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Aprobador")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("aprobador");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("MontoMaximoCrc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_maximo_crc");

                    b.Property<decimal>("MontoMinimoCrc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_minimo_crc");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("MontoMinimoCrc")
                        .IsUnique()
                        .HasDatabaseName("ux_niveles_aprobacion_monto_minimo");

                    b.ToTable("niveles_aprobacion", null, t =>
                        {
                            t.HasCheckConstraint("ck_niveles_aprobacion_minimo_positivo", "monto_minimo_crc > 0");

                            t.HasCheckConstraint("ck_niveles_aprobacion_rango_coherente", "monto_maximo_crc IS NULL OR monto_maximo_crc >= monto_minimo_crc");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("6f1f4d3e-0f2a-4c5d-9c6b-1a2b3c4d5e01"),
                            Aprobador = "Encargado de área",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MontoMaximoCrc = 999999.99m,
                            MontoMinimoCrc = 0.01m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6f1f4d3e-0f2a-4c5d-9c6b-1a2b3c4d5e02"),
                            Aprobador = "Gerencia",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MontoMaximoCrc = 9999999.99m,
                            MontoMinimoCrc = 1000000.00m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        },
                        new
                        {
                            Id = new Guid("6f1f4d3e-0f2a-4c5d-9c6b-1a2b3c4d5e03"),
                            Aprobador = "Junta Directiva",
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            MontoMinimoCrc = 10000000.00m,
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.Oferta", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FechaRegistro")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_registro");

                    b.Property<Guid>("LicitacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("licitacion_id");

                    b.Property<decimal>("MontoOfertadoCrc")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("monto_ofertado_crc");

                    b.Property<Guid>("ProveedorId")
                        .HasColumnType("uuid")
                        .HasColumnName("proveedor_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ProveedorId");

                    b.HasIndex("LicitacionId", "ProveedorId")
                        .IsUnique()
                        .HasDatabaseName("ux_ofertas_licitacion_proveedor");

                    b.HasIndex("LicitacionId", "MontoOfertadoCrc", "FechaRegistro")
                        .HasDatabaseName("ix_ofertas_licitacion_monto_fecha");

                    b.ToTable("ofertas", null, t =>
                        {
                            t.HasCheckConstraint("ck_ofertas_monto_positivo", "monto_ofertado_crc > 0");
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.Proveedor", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre");

                    b.Property<string>("NombreNormalizado")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("nombre_normalizado");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("NombreNormalizado")
                        .IsUnique()
                        .HasDatabaseName("ux_proveedores_nombre_normalizado")
                        .HasFilter("deleted_at IS NULL");

                    b.ToTable("proveedores", null, t =>
                        {
                            t.HasCheckConstraint("ck_proveedores_nombre_no_vacio", "length(btrim(nombre)) > 0");
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.TipoCambio", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<decimal>("CrcPorUsd")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("crc_por_usd");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FechaVigencia")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_vigencia");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Activo")
                        .IsUnique()
                        .HasDatabaseName("ux_tipos_cambio_activo")
                        .HasFilter("activo");

                    b.HasIndex("FechaVigencia")
                        .HasDatabaseName("ix_tipos_cambio_fecha_vigencia");

                    b.ToTable("tipos_cambio", null, t =>
                        {
                            t.HasCheckConstraint("ck_tipos_cambio_valor_positivo", "crc_por_usd > 0");
                        });

                    b.HasData(
                        new
                        {
                            Id = new Guid("8a2b6c4d-1e3f-4a5b-8c9d-0e1f2a3b4c05"),
                            Activo = true,
                            CrcPorUsd = 520.0000m,
                            CreatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            FechaVigencia = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            UpdatedAt = new DateTimeOffset(new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            Version = 1
                        });
                });

            modelBuilder.Entity("Licitaciones.Infrastructure.Persistencia.CatalogoEstadoLicitacion", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("descripcion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("nombre");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique()
                        .HasDatabaseName("ux_estados_licitacion_nombre");

                    b.ToTable("estados_licitacion", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Descripcion = "Licitación en preparación; admite edición y no acepta ofertas.",
                            Nombre = "Borrador"
                        },
                        new
                        {
                            Id = 1,
                            Descripcion = "Licitación publicada; acepta ofertas hasta la fecha de cierre.",
                            Nombre = "Publicada"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Licitación cerrada; estado terminal que conserva las ofertas como evidencia.",
                            Nombre = "Cerrada"
                        });
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.Licitacion", b =>
                {
                    b.HasOne("Licitaciones.Infrastructure.Persistencia.CatalogoEstadoLicitacion", null)
                        .WithMany()
                        .HasForeignKey("Estado")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_licitaciones_estado");
                });

            modelBuilder.Entity("Licitaciones.Domain.Entidades.Oferta", b =>
                {
                    b.HasOne("Licitaciones.Domain.Entidades.Licitacion", "Licitacion")
                        .WithMany()
                        .HasForeignKey("LicitacionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_licitacion");

                    b.HasOne("Licitaciones.Domain.Entidades.Proveedor", "Proveedor")
                        .WithMany()
                        .HasForeignKey("ProveedorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ofertas_proveedor");

                    b.Navigation("Licitacion");

                    b.Navigation("Proveedor");
                });
#pragma warning restore 612, 618
        }
    }
}
